Hospital_Management/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital_Management.Data;
using Hospital_Management.Models;
using Microsoft.AspNetCore.Authorization;
using YourProject.Attributes;

namespace Hospital_Management.Controllers
{
    [Authorize]
    public class DoctorsController : Controller
    {
        private readonly HealthCareDbContext _context;

        public DoctorsController(HealthCareDbContext context)
        {
            _context = context;
        }

        // GET: Doctors
        
        public async Task<IActionResult> Index()
        {
            var healthCareDbContext = _context.Doctors
                .Include(d => d.User)
                .Include(d => d.DoctorSpecialties)
                .ThenInclude(ds => ds.Specialty);
            return View(await healthCareDbContext.ToListAsync());
        }
        // GET: Doctors/Details/5
        [AdminOnly]
        [PatientOnly]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.DoctorID == id);
            if (doctor == null)
            {
                return NotFound();
            }

            return View(doctor);
        }


        [AdminOnly]
        public IActionResult Create()
        {
            // Fetch users who have the role "Doctor"
            var doctorUsers = _context.Users.Where(u => u.UserType == "Doctor").ToList();

            ViewData["UserID"] = new SelectList(doctorUsers, "UserID", "UserID");
            ViewBag.DoctorName = string.Empty;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminOnly]
        public async Task<IActionResult> Create([Bind("DoctorID,UserID,Name,Gender,Experience,AboutDoctor")] Doctor doctor)
        {
     
            doctor.User = await _context.Users.FirstOrDefaultAsync(u => u.UserID == doctor.UserID && u.UserType == "Doctor");

            if (doctor.User == null)
            {
                ModelState.AddModelError("UserID", "Selected user is not a doctor.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(doctor);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Doctor Created Successfully";
                    return RedirectToAction(nameof(Index));
                }catch(Exception ex)
                {
                    TempData["error"] = "Something went wrong !!";
                }
            }

            var doctorUsers = _context.Users.Where(u => u.UserType == "Doctor").ToList();
            ViewData["UserID"] = new SelectList(doctorUsers, "UserID", "Email", doctor.UserID);
            
            return View(doctor);
        }




        // GET: Doctors/Edit/5
        [AdminOnly]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Doctors == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email", doctor.UserID);
            return View(doctor);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [AdminOnly]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorID,UserID,Name,Gender,Experience,AboutDoctor")] Doctor doctor)
        {
            if (id != doctor.DoctorID)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctor);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Doctor details edited Successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["error"] = "Something went wrong!!";
                    if (!DoctorExists(doctor.DoctorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email", doctor.UserID);
            return View(doctor);
        }

       
        [AdminOnly]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctor = await _context.Doctors
                .FirstOrDefaultAsync(m => m.UserID == id);
            doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            try
            {
                _context.Doctors.Remove(doctor);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Doctor deleted successfully" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Failed to delete Doctor: {ex.Message}" });
            }


        }

        private bool DoctorExists(int id)
        {
          return (_context.Doctors?.Any(e => e.DoctorID == id)).GetValueOrDefault();
        }

        // GET: Doctors/GetDoctorName/5
        [HttpGet]
        public async Task<IActionResult> GetDoctorName(int id)
        {
            var doctorName = await _context.Users
                .Where(u => u.UserID == id)
                .Select(u => u.Username)
                .FirstOrDefaultAsync();

            return Json(doctorName);
        }

    }
}

Hospital_Management/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital_Management.Data;
using Hospital_Management.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace Hospital_Management.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private readonly HealthCareDbContext _context;

        public PatientsController(HealthCareDbContext context)
        {
            _context = context;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var role = User.FindFirstValue(ClaimTypes.Role);
            List<Patient> patients;

            if (role == "Patient")
            {
                patients = await _context.Patients
                    .Include(p => p.User)
                    .Where(p => p.UserID == Convert.ToInt32(userId)) 
                    .ToListAsync();
            }
            else if (role == "Admin")
            {
                patients = await _context.Patients
                    .Include(p => p.User) 
                    .ToListAsync();
            }
            else if (role == "Doctor")
            {
                var doctor = await _context.Doctors.FirstOrDefaultAsync(d => d.UserID == Convert.ToInt32(userId));
                if (doctor != null)
                {
                    patients = await _context.Appointments
                        .Include(a => a.Patient)
                        .Where(a => a.DoctorID == doctor.DoctorID)
                        .Select(a => a.Patient)
                        .Distinct()
                        .ToListAsync();
                }
                else
                {
                    patients = new List<Patient>();
                }
            }
            else
            {
                patients = new List<Patient>();
            }

            return View(patients);
        }


        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Patients == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PatientID == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            /*ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email");
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _context.Users.Find(userId);

            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email", userId);
            ViewBag.UserName = user?.Username;
            ViewBag.UserEmail = user?.Email;*/
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatientID,Name,DOB,Gender,BloodGroup,Address")] Patient patient)
        {
           
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            patient.UserID = Convert.ToInt32(userId);

            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();
                TempData["success"] = "Patient tCreated Successfully";
                return RedirectToAction(nameof(Index));
            }

            var errors = ModelState.Values.SelectMany(x => x.Errors);
            foreach (var error in errors)
            {
                Console.WriteLine(error.ErrorMessage);
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email", patient.UserID);
            return View(patient);
        }
        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Patients == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            ViewBag.UserName = patient.Name;
            
            return View(patient);
        }

        // POST: Patients/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatientID,UserID,Name,DOB,Gender,BloodGroup,Address")] Patient patient)
        {
            if (id != patient.PatientID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                    TempData["success"] = "Patient details edited successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.PatientID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.Users, "UserID", "Email", patient.UserID);
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patients
                .FirstOrDefaultAsync(m => m.UserID == id);
            patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            try
            {
                _context.Patients.Remove(patient);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Patient details deleted successfully" });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = $"Failed to delete patient details: {ex.Message}" });
            }


        }

        private bool PatientExists(int id)
        {
          return (_context.Patients?.Any(e => e.PatientID == id)).GetValueOrDefault();
        }
    }
}

Hospital_Management/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor

@{
    var userName = HttpContextAccessor.HttpContext.User.Identity.Name;
    var role = User.FindFirstValue(ClaimTypes.Role);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hospital_Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hospital_Management.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.12.2/dist/sweetalert2.all.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.12.2/dist/sweetalert2.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/confirmation.js"></script>
</head>
<body class="parentbody">
    <header class="bg-black">
        <nav class="text-dark  navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">

            <span class="text-white btn btn-outline-light fw-bold mx-2" style="white-space: nowrap;"><i class="fa-regular fa-hospital"></i> Novi Hospital</span>

            <div class="row container-fluid mx-5 login-details">
           
                <ul class="navbar-nav navitems">
                   
                    @if (!string.IsNullOrEmpty(userName))
                    {

                        <span class=" btn btn-light text-dark mx-1"><span style="white-space: nowrap;" class="fw-bold " style="white-space: nowrap;">@role : </span> @userName</span>

                            <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                <button type="submit" class="btn btn-success mx-4 fw-bold">Logout</button>
                            </form>
                     
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="btn btn-primary fw-bold" href="/Account/Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container-fluid ">
        <div class="row">
            @if (role != null)
            {
                <div class="col-md-2">
                    <partial name="_SideNav" />
                </div>
            }
            <div class="col-md-10">
                <partial name="_Notification" />
                <div class="content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted fw-bold bg-dark">
        <div class="container">
            &copy; 2024 - Novi Hospital
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hospital_Management/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.success('@TempData["success"]');



    </script>
    
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        toastr.error('@TempData["error"]');
    </script>
}

Hospital_Management/Views/Shared/_SideNav.cshtml
@{
    var userType = Context.Session.GetString("UserType");
}


<div class="sidebar">
    
    @if (userType == "Admin")
    {
        <div class="list-group">
            <a asp-controller="Home" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-house"></i>   Home</a>
            <a asp-controller="Admin" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-user"></i>    Users</a>
            <a asp-controller="Specialties" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-book-bible"></i>    Speciality</a>
            <a asp-controller="Patients" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-hospital-user"></i>    Patient Details </a>
            <a asp-controller="Appointments" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-regular fa-calendar-check"></i>    Appointment</a>
            <a asp-controller="Doctors" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-user-doctor"></i>  Doctors</a>
            <a asp-controller="DoctorSpecialties" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-stethoscope"></i>    DoctorsSpeciality</a>
        </div>
    }

    
    @if (userType == "Patient")
    {
        <div class="list-group">
            <a asp-controller="Home" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-house"></i>   Home</a>
            <a asp-controller="Patients" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-hospital-user"></i>    Register as Patient </a>
            <a asp-controller="Appointments" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-regular fa-calendar-check"></i>    Appointment</a>
            <a asp-controller="Doctors" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-user-doctor"></i>    Doctors</a>
        </div>
    }

    
    @if (userType == "Doctor")
    {
        <div class="list-group">
            <a asp-controller="Home" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-house"></i>   Home</a>
            <a asp-controller="Appointments" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-regular fa-calendar-check"></i>    Appointments</a>
            <a asp-controller="Patients" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-hospital-user"></i>    Patient Details </a>
            <a asp-controller="Doctors" asp-action="Index" class="list-group-item list-group-item-action"><i class="fa-solid fa-user-doctor"></i>   Doctors</a>
        </div>
    }
</div>