Hospital_Management/Controllers/DoctorSpecialtiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital_Management.Data;
using Hospital_Management.Models;
using Microsoft.AspNetCore.Authorization;
using YourProject.Attributes;

namespace Hospital_Management.Controllers
{
    [Authorize]
    [AdminOnly]
    public class DoctorSpecialtiesController : Controller
    {
        private readonly HealthCareDbContext _context;

        public DoctorSpecialtiesController(HealthCareDbContext context)
        {
            _context = context;
        }

        // GET: DoctorSpecialties
        public async Task<IActionResult> Index()
        {
            var healthCareDbContext = _context.DoctorSpecialties.Include(d => d.Doctor).Include(d => d.Specialty);
            return View(await healthCareDbContext.ToListAsync());
        }

        // GET: DoctorSpecialties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.DoctorSpecialties == null)
            {
                return NotFound();
            }

            var doctorSpecialty = await _context.DoctorSpecialties
                .Include(d => d.Doctor)
                .Include(d => d.Specialty)
                .FirstOrDefaultAsync(m => m.DoctorSpecialtyID == id);
            if (doctorSpecialty == null)
            {
                return NotFound();
            }

            return View(doctorSpecialty);
        }

        // GET: DoctorSpecialties/Create
        public IActionResult Create()
        {
            ViewData["DoctorID"] = new SelectList(_context.Doctors, "DoctorID", "Name");
            ViewData["SpecialtyID"] = new SelectList(_context.Specialties, "SpecialtyID", "SpecialtyName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorSpecialtyID,DoctorID,SpecialtyID")] DoctorSpecialty doctorSpecialty)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(doctorSpecialty);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Doctor Specialization added Successfully";
                    return RedirectToAction(nameof(Index));
                }
                catch(Exception ex)
                {
                    TempData["error"] = "Something went wrong";
                }
                
            }
            var errors = ModelState.Values.SelectMany(u => u.Errors);
            foreach(var error in errors)
            {
                Console.WriteLine(error.ErrorMessage);
            }
            ViewData["DoctorID"] = new SelectList(_context.Doctors, "DoctorID", "Gender", doctorSpecialty.DoctorID);
            ViewData["SpecialtyID"] = new SelectList(_context.Specialties, "SpecialtyID", "SpecialtyName", doctorSpecialty.SpecialtyID);
            return View(doctorSpecialty);
        }

        // GET: DoctorSpecialties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DoctorSpecialties == null)
            {
                return NotFound();
            }

            var doctorSpecialty = await _context.DoctorSpecialties.FindAsync(id);
            if (doctorSpecialty == null)
            {
                return NotFound();
            }
            ViewData["DoctorID"] = new SelectList(_context.Doctors, "DoctorID", "Name", doctorSpecialty.DoctorID);
            ViewData["SpecialtyID"] = new SelectList(_context.Specialties, "SpecialtyID", "SpecialtyName", doctorSpecialty.SpecialtyID);
            return View(doctorSpecialty);
        }

        // POST: DoctorSpecialties/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorSpecialtyID,DoctorID,SpecialtyID")] DoctorSpecialty doctorSpecialty)
        {
            if (id != doctorSpecialty.DoctorSpecialtyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctorSpecialty);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Doctor Specialization edited Successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["error"] = "Something went wrong while editing!!";
                    if (!DoctorSpecialtyExists(doctorSpecialty.DoctorSpecialtyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                    
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorID"] = new SelectList(_context.Doctors, "DoctorID", "Name", doctorSpecialty.DoctorID);
            ViewData["SpecialtyID"] = new SelectList(_context.Specialties, "SpecialtyID", "SpecialtyName", doctorSpecialty.SpecialtyID);
            return View(doctorSpecialty);
        }

 

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speciality = await _context.DoctorSpecialties
                .FirstOrDefaultAsync(m => m.DoctorSpecialtyID == id);
            speciality = await _context.DoctorSpecialties.FindAsync(id);
            if (speciality == null)
            {
                return NotFound();
            }
            try
            {
                _context.DoctorSpecialties.Remove(speciality);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Doctor Specialization deleted successfully" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Failed to delete Doctor Specialization: {ex.Message}" });
            }


        }

        private bool DoctorSpecialtyExists(int id)
        {
          return (_context.DoctorSpecialties?.Any(e => e.DoctorSpecialtyID == id)).GetValueOrDefault();
        }
    }
}

Hospital_Management/Views/DoctorSpecialties/Create.cshtml
@model Hospital_Management.Models.DoctorSpecialty

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Add Specialization</h2>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group my-3">
                    <label asp-for="DoctorID" class="control-label my-2"></label>
                    <select asp-for="DoctorID" class="form-control" asp-items="ViewBag.DoctorID"></select>
                </div>
                <div class="form-group my-3">
                    <label asp-for="SpecialtyID" class="control-label my-2"></label>
                    <select asp-for="SpecialtyID" class="form-control" asp-items="ViewBag.SpecialtyID"></select>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary w-25">Add Specialization</button>
                    <a asp-action="Index" class="btn btn-danger w-25">Back </a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Hospital_Management/Views/DoctorSpecialties/Edit.cshtml
@model Hospital_Management.Models.DoctorSpecialty

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Edit Specialization</h2>
            <form asp-action="Edit">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="DoctorSpecialtyID" />
                <div class="form-group">
                    <label asp-for="DoctorID" class="control-label my-3"></label>
                    <div class="text-center">
                        <select asp-for="DoctorID" class="form-control" asp-items="ViewBag.DoctorID"></select>
                    </div>
                    
                    <span asp-validation-for="DoctorID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SpecialtyID" class="control-label my-3"></label>
                    <div class=="text-center">
                        <select asp-for="SpecialtyID" class="form-control" asp-items="ViewBag.SpecialtyID"></select>
                    </div>
                    
                    <span asp-validation-for="SpecialtyID" class="text-danger"></span>
                </div>
                <div class="form-group text-center my-2">
                    <input type="submit" value="Save" class="btn w-25 btn-primary" />
                    <a asp-action="Index" class="btn btn-danger my-2 w-25">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital_Management/Views/DoctorSpecialties/Index.cshtml
@model IEnumerable<Hospital_Management.Models.DoctorSpecialty>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h2>Doctor Specializations</h2>
</div>

<p>
    <a asp-action="Create" class="btn btn-success">Add Doctor Specialization</a>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr class="text-center">
            <th>Doctor Name</th>
            <th>Specialization</th>
            <th>Modify</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.Doctor.Name</td>
                <td>@obj.Specialty.SpecialtyName</td>
                <td class="text-center">
                    <div class="w-75 btn-group" role="group">
                        <a asp-action="Edit" asp-route-id="@obj.DoctorSpecialtyID" class="btn btn-primary mx-2">
                            <i class="bi bi-pen-fill"></i>Edit
                        </a>

                        <button type="button" class="btn btn-danger mx-2" onclick="ConfirmationAlert('@Url.Action("Delete", "DoctorSpecialties", new { id = obj.DoctorSpecialtyID })')">
                            <i class="bi bi-trash-fill"></i> Delete
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>