Hospital_Management/Controllers/SpecialtiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital_Management.Data;
using Hospital_Management.Models;
using Microsoft.AspNetCore.Authorization;
using YourProject.Attributes;

namespace Hospital_Management.Controllers
{
    [Authorize]
    [AdminOnly]
    public class SpecialtiesController : Controller
    {
        private readonly HealthCareDbContext _context;

        public SpecialtiesController(HealthCareDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
              return _context.Specialties != null ? 
                          View(await _context.Specialties.ToListAsync()) :
                          Problem("Entity set 'HealthCareDbContext.Specialties'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Specialties == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties
                .FirstOrDefaultAsync(m => m.SpecialtyID == id);
            if (specialty == null)
            {
                return NotFound();
            }

            return View(specialty);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SpecialtyID,SpecialtyName")] Specialty specialty)
        {
            if (ModelState.IsValid)
            {

                _context.Add(specialty);
                await _context.SaveChangesAsync();
                
                TempData["Success"] = "Specialization Created Successfully";
                
                return RedirectToAction(nameof(Index));
            }

            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var error in errors)
            {
                Console.WriteLine(error.ErrorMessage);
            }

            return View(specialty);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Specialties == null)
            {
                return NotFound();
            }

            var specialty = await _context.Specialties.FindAsync(id);
            if (specialty == null)
            {
                return NotFound();
            }
            return View(specialty);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SpecialtyID,SpecialtyName")] Specialty specialty)
        {
            if (id != specialty.SpecialtyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(specialty);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = "Specialization Edited Successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialtyExists(specialty.SpecialtyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(specialty);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var speciality = await _context.Specialties
                .FirstOrDefaultAsync(m => m.SpecialtyID == id);
            speciality = await _context.Specialties.FindAsync(id);
            if (speciality == null)
            {
                return NotFound();
            }
            try
            {
                _context.Specialties.Remove(speciality);
                await _context.SaveChangesAsync();
                return Json(new { success = true, message = "Specialization deleted successfully" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Failed to delete Specialization: {ex.Message}" });
            }
        }

        private bool SpecialtyExists(int id)
        {
          return (_context.Specialties?.Any(e => e.SpecialtyID == id)).GetValueOrDefault();
        }
    }
}

Hospital_Management/Views/Specialties/Create.cshtml
@model Hospital_Management.Models.Specialty

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Add Specialization</h2>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group my-3 text-center">
                    <label asp-for="SpecialtyName" class="control-label my-2">Specialty Name</label>
                    
                     <input asp-for="SpecialtyName" class="form-control ml-5" />
                 
                    <span asp-validation-for="SpecialtyName" class="text-danger"></span>
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary w-25">Create Specialty</button>
                    <a asp-action="Index" class="btn btn-danger w-25">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Hospital_Management/Views/Specialties/Edit.cshtml
@model Hospital_Management.Models.Specialty

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Edit Specialization</h2>
            <form asp-action="Edit">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="SpecialtyID" />
                <div class="form-group my-3 text-center">
                    <label asp-for="SpecialtyName" class="control-label my-2">Specialty Name</label>

                    <input asp-for="SpecialtyName" class="form-control ml-5" />

                    <span asp-validation-for="SpecialtyName" class="text-danger"></span>
                </div>

                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary w-25">Edit </button>
                    <a asp-action="Index" class="btn btn-danger w-25">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital_Management/Views/Specialties/Index.cshtml
@model IEnumerable<Hospital_Management.Models.Specialty>

@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h2>Specialization</h2>
</div>

<p>
    <a asp-action="Create" class="btn btn-success">Add Specialization</a>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr class="text-center">
            <th>Speciality ID</th>
            <th>Specialization</th>
            <th>Modify</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr>
                <td>@obj.SpecialtyID</td>
                <td>@obj.SpecialtyName</td>
                <td class="text-center">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Specialties" asp-action="Edit" asp-route-id="@obj.SpecialtyID" class="btn btn-primary mx-2">
                            <i class="bi bi-pen-fill"></i>Edit
                        </a>

                        <button type="button" class="btn btn-danger mx-2" onclick="ConfirmationAlert('@Url.Action("Delete", "Specialties", new { id = obj.SpecialtyID })')">
                            <i class="bi bi-trash-fill"></i> Delete
                        </button>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>